# Generated by Django 2.0.3 on 2018-05-10 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.CharField(blank=True, max_length=100, null=True, verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=300, verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='impress-art', verbose_name='Imagem')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor')),
                ('tipo', models.CharField(choices=[('IP', 'impressão'), ('AT', 'criação de arte')], max_length=2, verbose_name='Tipo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
            ],
            options={
                'ordering': ['description'],
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
    ]
