# Generated by Django 2.0.3 on 2018-05-11 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceImpress',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Service')),
                ('value_creation_art', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
            ],
            bases=('core.service',),
        ),
    ]
