# Generated by Django 2.0.3 on 2018-05-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_service_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceimpress',
            name='deadline',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Prazo para criação de arte'),
        ),
    ]
