# Generated by Django 2.0.3 on 2018-05-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_serviceimpress_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceimpress',
            name='deadline',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Prazo em dias para criação de arte'),
        ),
    ]
