# Generated by Django 2.0.3 on 2018-05-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180518_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='observations',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Observações'),
        ),
    ]
