# Generated by Django 2.0.3 on 2018-05-18 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_service_observations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='observations',
        ),
    ]
