# Generated by Django 2.0.3 on 2018-05-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_service_observations'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceimpress',
            name='date_solicitation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de solicitação da arte'),
        ),
    ]
