# Generated by Django 2.0.3 on 2018-05-18 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_serviceimpress_date_solicitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceimpress',
            name='date_solicitation',
        ),
    ]
