# Generated by Django 2.0.3 on 2018-05-11 09:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderArt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, editable=False)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Valor R$')),
                ('status', models.CharField(choices=[('FZ', 'finalizado'), ('EA', 'em andamento'), ('CL', 'cancelado'), ('PG', 'pago')], default='EA', max_length=2, verbose_name='Status do Pedido')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pedidos Criação de Arte',
                'ordering': ['date'],
                'verbose_name': 'Pedido Criação de Arte',
            },
        ),
        migrations.CreateModel(
            name='OrderImpress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, editable=False)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor R$')),
                ('status', models.CharField(choices=[('FZ', 'finalizado'), ('EA', 'em andamento'), ('CL', 'cancelado'), ('PG', 'pago')], default='EA', max_length=2, verbose_name='Status do Pedido')),
                ('delivery_address_is_the_same', models.BooleanField(default=True, verbose_name='Entregar no endereço cadastrado')),
                ('logradouro_delivery', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Rua/Avenida')),
                ('numero_delivery', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Número')),
                ('cep_delivery', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='CEP')),
                ('complemento_delivery', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Complamento')),
                ('bairro_delivery', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Bairro')),
                ('cidade_delivery', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Cidade')),
                ('estado_delivery', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Estado')),
                ('value_art_creation', models.CharField(max_length=10, verbose_name='Valor para criação de arte')),
                ('deadline', models.PositiveSmallIntegerField(verbose_name='Prazo para criação de arte')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pedidos Impressão',
                'ordering': ['date'],
                'verbose_name': 'Pedido Impressão',
            },
        ),
        migrations.CreateModel(
            name='OrderItemArt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, editable=False, verbose_name='Quantidade')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('image_example1', models.FileField(blank=True, null=True, upload_to='image-example', verbose_name='Imagem de Exemplo 1')),
                ('image_example2', models.FileField(blank=True, null=True, upload_to='image-example', verbose_name='Imagem de Exemplo 2')),
                ('image_example3', models.FileField(blank=True, null=True, upload_to='image-example', verbose_name='Imagem de Exemplo 3')),
                ('image_example4', models.FileField(blank=True, null=True, upload_to='image-example', verbose_name='Imagem de Exemplo 4')),
                ('image_view', models.ImageField(blank=True, null=True, upload_to='image_view', verbose_name='Imagem para Visualização')),
                ('approved', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('final_work', models.FileField(blank=True, null=True, upload_to='final_work', verbose_name='Trabalho Final')),
                ('orderArt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checkout.OrderArt')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Service')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemImpress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, editable=False, verbose_name='Quantidade')),
                ('art', models.FileField(blank=True, null=True, upload_to='order-item-impress', verbose_name='Logo')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='checkout.OrderImpress')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Service')),
            ],
            options={
                'verbose_name_plural': 'Impressões',
                'ordering': ['order'],
                'verbose_name': 'Impressão',
            },
        ),
    ]
