# Generated by Django 2.0.3 on 2018-05-17 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderimpress',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='orderimpress',
            name='value_art_creation',
        ),
    ]
