# Generated by Django 2.0.3 on 2018-05-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderimpress',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID da transação'),
        ),
    ]
