# Generated by Django 2.0.3 on 2018-05-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_client', '0002_auto_20180517_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemimpress',
            name='creation_art_solicited',
            field=models.BooleanField(default=False, verbose_name='Criação de arte solicitada'),
        ),
    ]
