# Generated by Django 2.0.3 on 2018-05-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_client', '0002_orderimpress_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderart',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID da transação'),
        ),
    ]
