# Generated by Django 2.0.3 on 2018-05-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_client', '0003_orderitemimpress_creation_art_solicited'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemimpress',
            name='observations',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Observações'),
        ),
    ]
