# Generated by Django 2.0.3 on 2018-05-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_client', '0004_orderitemimpress_observations'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemimpress',
            name='date_solicitation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de solicitação da arte'),
        ),
    ]
