# Generated by Django 2.0.3 on 2018-05-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_client', '0005_orderitemimpress_date_solicitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemart',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='orderitemart',
            name='image_view',
        ),
        migrations.AddField(
            model_name='orderitemimpress',
            name='image_example1',
            field=models.FileField(blank=True, null=True, upload_to='image-example', verbose_name='Imagem de Exemplo 1'),
        ),
        migrations.AddField(
            model_name='orderitemimpress',
            name='image_example2',
            field=models.FileField(blank=True, null=True, upload_to='image-example', verbose_name='Imagem de Exemplo 2'),
        ),
        migrations.AddField(
            model_name='orderitemimpress',
            name='image_example3',
            field=models.FileField(blank=True, null=True, upload_to='image-example', verbose_name='Imagem de Exemplo 3'),
        ),
        migrations.AddField(
            model_name='orderitemimpress',
            name='image_example4',
            field=models.FileField(blank=True, null=True, upload_to='image-example', verbose_name='Imagem de Exemplo 4'),
        ),
        migrations.AddField(
            model_name='orderitemimpress',
            name='model',
            field=models.FileField(blank=True, null=True, upload_to='order-item-impress', verbose_name='Logo'),
        ),
    ]
