# Generated by Django 2.0.3 on 2018-06-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_client', '0005_auto_20180608_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderimpress',
            name='status_pg',
            field=models.CharField(choices=[('1', 'Completo'), ('2', 'Aprovado'), ('3', 'Em Análise'), ('4', 'Devolvido'), ('5', 'Cancelado')], default='3', max_length=10, verbose_name='Status PagSeguro'),
        ),
    ]
