# Generated by Django 2.0.3 on 2018-05-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_client', '0006_auto_20180522_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemart',
            name='model',
            field=models.FileField(blank=True, null=True, upload_to='order-item-impress', verbose_name='Logo'),
        ),
    ]
