# Generated by Django 2.0.3 on 2018-05-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_client', '0007_orderitemart_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderart',
            name='model',
            field=models.FileField(blank=True, null=True, upload_to='orderArt_models'),
        ),
    ]
